# App Config ========================================================= #

app:

  # Release ================================================ #

  # RELEASE
  # The current site version for use in 'virtual versioned' URLs
  # and an Origin Pull CDN setup such as CloudFront. This method
  # does not require one to use 'invalidate' on every site update
  # and syncs automatically with Cloudfront, so you don't need to
  # use S3.
  #
  # Exactly 6 digit integer. Increment by 1 for every LIVE release.
  #
  # Release id, if not set or null, the current day's date will be
  # used with two digit century; given 2025/01/15, release will
  # equal 250115
  release: 100012

  # Mode =================================================== #

  # MODE
  # Switches some URL paths to Relative, Absolute or CDN.
  # Options: (development|production)
  mode: production

  # CDN ==================================================== #

  # CDN HOSTS
  # Order matters. Pos 1 is host 0, Pos 2 is host 1 etc.
  # Change to CNAME hosts if you don't need SSL.
  cdn_hosts:
    - d4yblnny9djlk.cloudfront.net
    - d1hhryxrxet0hj.cloudfront.net
    - d2821b5m3tucp6.cloudfront.net
    - d3dfdi6g2ekadr.cloudfront.net

  # Locale and encoding ==================================== #
  dir: rtl
  lang: en-US
  locale: en_US
  encoding: utf-8
  viewport: 'width=device-width'

  # Name (Brand), Tagline and Meta Image (Og) ============== #
  name: Jhaura Wachsman
  tagline: 'Web Developer, Internet Marketer'
  description: |
    Jhaura Wachsman is a web developer who delivers modern mobile-first web applications using today's most advanced technologies and techniques so that your website delivers an exceptional user experience.

  # Contact and Domain ===================================== #
  email: jw@jhaurawachsman.com
  domain: jhaurawachsman.com

  # Default author for Posts =============================== #
  author:
    name: Jhaura Wachsman
    link: twitter.com/JhauraWachsman

  # Social Media User Names (Not full URL) ================= #
  github: jhauraw
  twitter: JhauraWachsman
  facebook: JhauraWachsman
  youtube: jhaurawachsman
  gplus: 103492502746159725544
  pinterest: jhaurawachsman
  linkedin: jhaurawachsman
  stacko: 2201020

  # Feedburner Feed Name =================================== #
  feed-name: jhaurawachsman

  # Meta Admin / Verify IDs =================================#
  facebook-admin: 1550453047
  facebook-appid: 251689391563684
  gplus-publisher: 103492502746159725544
  disqus_user: jhaurawachsman

  # Analytics / Metrics ==================================== #
  google-analytics-id: UA-17276272-1

  # Categories ============================================= #
  categories:
    - web development
    - internet marketing
    - workflow
    - lifestyle
    - business
    - news

  # Nav Panel ============================================== #
  navpanel:
    -
      slug: articles
      name: Articles
      icon: beaker
    -
      slug: work
      name: Work
      icon: picture
    -
      slug: resume
      name: Résumé
      icon: briefcase
    -
      slug: contact
      name: Contact
      icon: envelope
    -
      slug: search
      name: Search
      icon: search

# Jekyll Config ====================================================== #

# TIMEZONE
# Set the timezone (TZ ENV variable) you want the site to run from.
# http://en.wikipedia.org/wiki/Tz_database
timezone: America/Los_Angeles

# URL
# Used any place a where an absolute URL is required.
#
# REQUIRED if you want OG:TYPE meta tags, XML feed and
# robots.txt sitemap link.
#
# If using jekyll --server locally, use: http://localhost:PORT
# Default PORT is usually 4000
#
# If using MAMP/XAMP locally, use your local host name such as
# sitename.localhost
#
# For production, set to the HTTP server domain.
# Be sure to use http://
#
# NO Trailing-Slash
# DEV: localhost:4000
# PROD: jhaurawachsman.com
url: http://jhaurawachsman.com

# BASEURL
# To run the ENTIRE site from a sub-dir, e.g., /sub
#
# This theme uses ABSOLUTE URLs in places like the XML Feed and
# OG tags, so we need to set it to null (no quotes) explicitly
# so that the Jekyll default of '/' doesn't mess up our URLs
# with // (double-slashes).
#
# YES Front-Slash. NO Trailing-Slash. Otherwise set to null.
baseurl: null

# PERMALINK
# You can use a directory name here to have just the _posts
# served from an sub-directory, e.g., /blog/
#
# In that case, your permalink value might be: /blog/:title/
#
# NOTE: This is different from the baseurl variable above;
# as it only affects the _posts directory, a.k.a., Blog.
#
# YES Front-Slash. YES Trailing-Slash
permalink: /:year/:title/

paginate_path: /articles/page:num/
paginate: 25

#lsi: true
markdown: redcarpet
pygments: true

include: ['.htaccess']
exclude: ['TODO.md', 'CHANGELOG.md', 'README.md', 'LICENSE-GPL', 'LICENSE-CCA', 'Gruntfile.js', '*.json', 'node_modules', 'bower_components']
